# Tonika: A distributed social networking platform
# Copyright (C) 2010 Petar Maymounkov <petar@5ttt.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


include $(GOROOT)/src/Make.$(GOARCH)

TARG=tonika/fe
GOFILES=\
	api-accept.go\
	api-add.go\
	api-live.go\
	api-monitor.go\
	api-myinfo.go\
	api-revoke.go\
	api-update.go\
	accept.go\
	admin.go\
	add.go\
	edit.go\
	bug.go\
	monitor.go\
	reinvite.go\
	reqtype.go\
	fe.go\
	root.go\
	util.go\
	viavault.go\

include $(GOROOT)/src/Make.pkg
